
version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data of product, sales and shipping info   
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: table for sales of Greenweez
      - name: products
        identifier: raw_gz_product
        description: table for products data of Greenweez
      - name: ship
        identifier: raw_gz_ship
        description: table for shipping data of Greenweez
